//Innehåller klasslista för export
exports.all = 
[
{ "firstname": "Mattias", "lastname": "Alm", "email": "Mattias.Alm@yh.nackademin.se" },
{ "firstname": "Erik", "lastname": "Thorsson", "email": "Erik.Thorsson@yh.nackademin.se" },
{ "firstname": "Hanna", "lastname": "Arefiardakani", "email": "Hanna.Arefiardakani@yh.nackademin.se" },
{ "firstname": "Linus", "lastname": "H\u00e4r\u00e9n", "email": "Linus.Haren@yh.nackademin.se" },
{ "firstname": "Dennis", "lastname": "Tarbiat", "email": "Dennis.Tarbiat@yh.nackademin.se" },
{ "firstname": "Robin", "lastname": "Lock", "email": "Robin.Lock@yh.nackademin.se" }, 
{ "firstname": "Anders", "lastname": "Kull", "email": "Anders.Kull@yh.nackademin.se" },
{ "firstname": "Johan", "lastname": "B\u00e4cklin", "email": "Johan.Backlin@yh.nackademin.se" },
{ "firstname": "Terese", "lastname": "Bod\u00e9rus", "email": "Terese.Boderus@yh.nackademin.se" },
{ "firstname": "Sirojiddin", "lastname": "Khamidullaev ", "email": "Sirojiddin.Khamidullaev@yh.nackademin.se" },
{ "firstname": "Zichun", "lastname": "Zhao", "email": "Zichun.Zhao@yh.nackademin.se" },
{ "firstname": "Sofia", "lastname": "Laas", "email": "Sofia.Laas@yh.nackademin.se" }, 
{ "firstname": "Alex", "lastname": "Saxena", "email": "Alex.Saxena@yh.nackademin.se" },
{ "firstname": "Alexander", "lastname": "Wikl\u00f6w", "email": "Alexander.Wiklow@yh.nackademin.se" },
{ "firstname": "Andreas", "lastname": "Warncke", "email": "Andreas.Warncke@yh.nackademin.se" },
{ "firstname": "Anton", "lastname": "Ottern\u00e4s", "email": "Anton.Otternas@yh.nackademin.se" },
{ "firstname": "Araceli", "lastname": "Prieto Gallego", "email": "Araceli.PrietoGallego@yh.nackademin.se" },
{ "firstname": "tollis", "lastname": "papadopoulos", "email": "tollis.papadopoulos@yh.nackademin.se" }, 
{ "firstname": "Bagher", "lastname": "Hosseini", "email": "Bagher.Hosseini@yh.nackademin.se" },
{ "firstname": "Claude", "lastname": "Loba", "email": "Claude.Loba@yh.nackademin.se" },
{ "firstname": "Daniel", "lastname": "Jansson", "email": "Daniel.Jansson@yh.nackademin.se" },
{ "firstname": "Elin", "lastname": "Horn", "email": "Elin.Horn@yh.nackademin.se" },
{ "firstname": "Emil", "lastname": "Sund\u00e9n", "email": "Emil.Sunden@yh.nackademin.se" },
{ "firstname": "Tom", "lastname": "Johansson", "email": "Tom.Johansson@yh.nackademin.se" }, 
{ "firstname": "Fosiya ", "lastname": "Giama", "email": "Fosiya.Giama@yh.nackademin.se" },
{ "firstname": "Gustav", "lastname": "Franchell", "email": "Gustav.Franchell@yh.nackademin.se" },
{ "firstname": "Jirawan", "lastname": "Sangthong", "email": "Jirawan.Sangthong@yh.nackademin.se" },
{ "firstname": "Jonathan", "lastname": "Ljung Perki\u00f6", "email": "Jonathan.LjungPerkio@yh.nackademin.se" },
{ "firstname": "Juliett", "lastname": "Busuioc", "email": "Juliett.Busuioc@yh.nackademin.se" },
{ "firstname": "Karl", "lastname": "\u00d6sterberg", "email": "Karl.Osterberg@yh.nackademin.se" },
{ "firstname": "Kenneth", "lastname": "Ellebring", "email": "Kenneth.Ellebring@yh.nackademin.se" },
{ "firstname": "Kimberley", "lastname": "Ahnlund Matthews", "email": "Kimberley.AhnlundMatthews@yh.nackademin.se" },
{ "firstname": "Lucas", "lastname": "Larsson", "email": "Lucas.Larsson2@yh.nackademin.se" },
{ "firstname": "Mette", "lastname": "af Ekenstam", "email": "Mette.afEkenstam@yh.nackademin.se" },
{ "firstname": "Vadzim", "lastname": "Kulikouski", "email": "Vadzim.Kulikouski@yh.nackademin.se" }, 
{ "firstname": "Miguel", "lastname": "Vallin", "email": "Miguel.Vallin@yh.nackademin.se" },
{ "firstname": "Mika", "lastname": "Munterud", "email": "Mika.Munterud@yh.nackademin.se" },
{ "firstname": "Noel", "lastname": "Perland", "email": "Noel.Perland@yh.nackademin.se" },
{ "firstname": "Patrik", "lastname": "Skantz", "email": "Patrik.Skantz@yh.nackademin.se" },
{ "firstname": "Rebecca", "lastname": "Fischer", "email": "Rebecca.Fischer@yh.nackademin.se" },
{ "firstname": "Sanaz", "lastname": "Effati Khajehha", "email": "Sanaz.EffatiKhajehha@yh.nackademin.se" }	
]